#!/usr/bin/env bash
if [ $# -eq 0 ]; then
	scheme=$(ls -1 schemes | sed 's/.yml$//' | fzf)
else
	scheme=$1
fi

termite_light="output/termite/base16-${scheme}.light.config"
termite_dark="output/termite/base16-${scheme}.dark.config"
vconsole_light="output/vconsole/base16-${scheme}.light.sh"
vconsole_dark="output/vconsole/base16-${scheme}.dark.sh"

echo "Applying ${scheme}..."

sed -i -ne "/### BEGIN COLORS/ {p; r $termite_light" -e ':a; n; /### END COLORS/ {p; b}; ba}; p' ~/.config/termite/config_light
sed -i -ne "/### BEGIN COLORS/ {p; r $termite_dark" -e ':a; n; /### END COLORS/ {p; b}; ba}; p' ~/.config/termite/config_dark

cat $vconsole_light > ~/.vconsole_light
cat $vconsole_dark > ~/.vconsole_dark

~/.local/bin/brighside
